Django2/personalWeb/pdf/urls.py
from django.urls import path
from . import views

# Assign appname for clarity
app_name = "pdf"

urlpatterns = [
    path('', views.pdf, name="pdf"),
] 

Django2/personalWeb/personalWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('blog/', include('blog.urls')),
    path('stock/', include('stock.urls')),
    path('todo/', include('todo.urls')),
    path('utube/', include('utube.urls')),
    path('pdf/', include('pdf.urls')),
    path('expense/', include('expense.urls')),
    path('heartattackclassification/', include('heartattackclassification.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django2/personalWeb/utube/urls.py
from django.urls import path
from . import views

# Assign appname for clarity
app_name = "utube"

urlpatterns = [
    path('', views.utube, name="utube"),
    path('download_video/', views.download_video, name='download_video'),
    path('show_video/<str:video_title>/', views.show_video, name='show_video'),
] 

Django2/personalWeb/utube/models.py
from django.db import models

# Create your models here.
class Video(models.Model):
    title = models.CharField(max_length=200)
    vid = models.FileField()

    def __str__(self):
        return self.title

Django2/personalWeb/utube/views.py
from django.shortcuts import render
import os
from django.conf import settings

# Create your views here.
def utube(request):
    path = os.path.join(settings.BASE_DIR, 'utube/static/utube')
    files = os.listdir(path)

    return render(request, 'utube/home.html', {'files': files})

from pytube import YouTube


def download_video(request):
    url = request.GET.get('url')
    yt = YouTube(url)

    stream = yt.streams.filter(progressive=True, file_extension='mp4').first()
    video_filename = stream.default_filename
    file_path = os.path.join(settings.BASE_DIR, 'utube/static/utube', video_filename)
    stream.download(os.path.dirname(file_path))

    return render(request, 'utube/home.html', {'status': 'Video downloaded successfully'})

import urllib.parse

def show_video(request, video_title):
    video_title = urllib.parse.unquote(video_title)
    video_path = os.path.join(settings.BASE_DIR, 'utube/static/utube/{}'.format(video_title))
    if os.path.isfile(video_path):
        return render(request, 'utube/show_video.html', {'video_title': video_title, 'video_path': video_path})

Django2/personalWeb/utube/templates/utube/home.html
<!-- Inheriting from main.html in the main project folder-->
{% extends 'main.html'%}

{% load static %}

{% block content %}

<div class="contianer text-center">
    <br>
    <h1>Youtube Video Downloader</h1>
    <br>
    <form action="{% url 'utube:download_video' %}" method="get">
        <input type="text" name="url">
        <button type="submit">Download Video</button>
    </form>
</div>

<h1 class="text-center">{{ status }}</h1>

<div class="container">
    <h2>List of Downloaded Videos</h2>
    <ul style="list-style-type: none;">
        {% for file in files %}
            <li><a href="{% url 'utube:show_video' video_title=file %}">{{ file }}</a></li>
        {% endfor %}
    </ul>
</div>


{% endblock %}

Django2/personalWeb/utube/templates/utube/show_video.html
<!-- Inheriting from main.html in the main project folder-->
{% extends 'main.html'%}
{% load static %}

{% block content %} 

<div class="container text-center">
    <h1>{{ video_title }}</h1>
    <video width="1280" height="720" controls>
        <source src="{% static 'utube/' %}{{ video_title }}" type="video/mp4">
    </video> 
    <br>
    <a href = "{% url 'utube:utube' %}">Back</a>
</div>


<hr>



{% endblock %}