Django2/personalWeb/pdf/urls.py
from django.urls import path
from . import views

# Assign appname for clarity
app_name = "pdf"

urlpatterns = [
    path('', views.pdf, name="pdf"),
] 

Django2/personalWeb/personalWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('blog/', include('blog.urls')),
    path('stock/', include('stock.urls')),
    path('todo/', include('todo.urls')),
    path('utube/', include('utube.urls')),
    path('pdf/', include('pdf.urls')),
    path('expense/', include('expense.urls')),
    path('heartattackclassification/', include('heartattackclassification.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django2/personalWeb/todo/urls.py
from django.urls import path
from . import views
from .views import list_tasks, create_task

# Assign appname for clarity
app_name = "todo"


urlpatterns = [
    path('', views.list_tasks, name='list_tasks'),
    path('tasks/', views.list_tasks, name='list_tasks'),
    path('create/', views.create_task, name='create_task'),
    path('delete_all/', views.delete_all, name='delete_all'),
    path('delete/<int:task_id>/', views.delete_task, name='delete_task'),
    #path('delete/<int:task_id>/', views.delete_task, name='delete_task'),
]

Django2/personalWeb/todo/models.py
from django.db import models
from django.utils import timezone

# Create your models here.
class Task(models.Model):
    title = models.CharField(max_length=200)
    date = models.DateField(default=timezone.now)
    completed = models.BooleanField(default=False)

    def __str__(self):
        return self.title

Django2/personalWeb/todo/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Task

# Create your views here.
def list_tasks(request):
    tasks = Task.objects.all()
    return render(request, 'todo/list.html', {'tasks': tasks})

def create_task(request):
    if request.method == 'POST':
        Task.objects.create(title=request.POST['title'])
        return redirect('todo:list_tasks')
    return render(request, 'todo/create.html')

def delete_all(request):
    Task.objects.all().delete()
    return redirect('todo:list_tasks')

def delete_task(request, task_id):
    task = Task.objects.get(id=task_id)
    task.delete()
    return redirect('todo:list_tasks')

Django2/personalWeb/todo/templates/todo/create.html
<!-- Inheriting from main.html in the main project folder-->
{% extends 'main.html'%}
{% load static %}

{% block content %}

<div class="container text-center">
  <h1>Create Task</h1>
  <form method="post">
    {% csrf_token %}
    <input type="text" name="title">
    <button type="submit">Create</button>
  </form>
</div>

{% endblock %}

Django2/personalWeb/todo/templates/todo/list.html
<!-- Inheriting from main.html in the main project folder-->
{% extends 'main.html'%}
{% load static %}

{% block content %}

<h1 class="text-center">Tasks</h1>
<div class="container text-center">
  <ul style="list-style-type: none;">
  {% for task in tasks %}
    <li>{{ task.date }} - {{ task.title }} | <a href="{% url 'todo:delete_task' task.id %}">Delete Task</a></li> 
  {% endfor %}
  </ul>
  <a href="{% url 'todo:create_task' %}">Create Task</a>

  <br>
  
  <form method="post" action="{% url 'todo:delete_all' %}">
    {% csrf_token %}
    <button type="submit">Delete All</button>
  </form>
</div>


<hr>

{% endblock %}