Django2/personalWeb/base/urls.py
from django.urls import path
from . import views

app_name = "base"

urlpatterns = [
    path('', views.landing, name="landing"),
    path('adminPage/', views.adminPage, name='adminPage'),
    path('contact/', views.contact, name="contact"),
    path('resume/', views.resume, name="resume"),
    path('ibm/', views.ibm, name="ibm"),
    path('publication/', views.publication, name="publication"),
    path('eid101/', views.eid101, name="eid101"),
    path('contact_submit/', views.contact_submit, name='contact_submit'),
    path('ml/', views.mlproj, name="mlproj"),
    path('cert/', views.cert, name="cert"),
    path('home/', views.home, name="home"),
    #path('room/', views.room, name="room"),

]

Django2/personalWeb/pdf/urls.py
from django.urls import path
from . import views

# Assign appname for clarity
app_name = "pdf"

urlpatterns = [
    path('', views.pdf, name="pdf"),
] 

Django2/personalWeb/personalWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('blog/', include('blog.urls')),
    path('stock/', include('stock.urls')),
    path('todo/', include('todo.urls')),
    path('utube/', include('utube.urls')),
    path('pdf/', include('pdf.urls')),
    path('expense/', include('expense.urls')),
    path('heartattackclassification/', include('heartattackclassification.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django2/personalWeb/base/models.py
from django.db import models

# Create your models here.
class Project(models.Model):
    # Django model fields
    title = models.CharField(max_length = 100)
    description = models.CharField(max_length = 250)
    image = models.ImageField(upload_to ='media/')
    url = models.URLField(blank = True)
    
    # Functions that displays title on the admin page
    def __str__(self):
        return self.title

class Skill(models.Model):
    title = models.CharField(max_length=50)
    def __str__(self):
        return self.title

class Publication(models.Model):
    # Django model fields
    title = models.CharField(max_length = 250)
    description = models.TextField()
    image = models.ImageField(upload_to ='media/')
    url = models.URLField(blank = True)
    
    # Functions that displays title on the admin page
    def __str__(self):
        return self.title

class ContactForm(models.Model):
    first_name = models.CharField(max_length=255, default='')
    last_name = models.CharField(max_length=255, default='')
    email = models.EmailField(default='')
    phone_number = models.CharField(max_length=255, default='')
    find = models.CharField(max_length=255, default='')
    additional_info = models.TextField(default='')
    file = models.FileField(upload_to='media/', default=None, blank=True, null=True)
    terms = models.BooleanField(default=False)

    def __str__(self):
        return self.email

class ML(models.Model):
    # Django model fields
    title = models.CharField(max_length = 250)
    description = models.TextField()
    tech = models.TextField()
    image = models.ImageField(upload_to ='media/')
    url = models.URLField(blank = True)
    
    # Functions that displays title on the admin page
    def __str__(self):
        return self.title

class Cert(models.Model):
    # Django model fields
    title = models.CharField(max_length = 250)
    date = models.DateField()
    url = models.URLField(blank = True)
    
    # Functions that displays title on the admin page
    def __str__(self):
        return self.title

Django2/personalWeb/base/views.py
from django.shortcuts import render
from .models import Project, Publication, Skill, ContactForm, ML, Cert


# Create your views here.
def home(request):
    projects = Project.objects.all()
    skills = Skill.objects.all().order_by('title')
    context = {'projects': projects, 'skills': skills}
    return render(request, 'base/home.html', context)

def publication(request):
    publications = Publication.objects.all()
    context = {'publications': publications}
    return render(request, 'base/publication.html', context)

def contact(request):
    return render(request, 'base/contact.html')

def resume(request):
    return render(request, 'base/resume.html')

def ibm(request):
    return render(request, 'base/IBMppt.html')

def eid101(request):
    return render(request, 'base/eid101.html')

def cert(request):
    certs = Cert.objects.all()
    context = {'certs': certs}
    return render(request, 'base/cert.html', context)

def landing(request):
    return render(request, 'base/landing.html')

# Admin
from django.urls import reverse
from django.shortcuts import redirect

def adminPage(request):
    admin_url = reverse('admin:index')
    return redirect(admin_url)

def mlproj(request):
    MLs = ML.objects.all()
    context = {'MLs': MLs}
    return render(request, 'base/mlproj.html', context)

def contact_submit(request):
    if request.method == 'POST':
        first_name = request.POST.get('firstName')
        last_name = request.POST.get('lastName')
        email = request.POST.get('email')
        phone = request.POST.get('phone')
        find = request.POST.get('find')
        info = request.POST.get('textBox')
        file = request.FILES.get('file')
        term = request.POST.get('term') == "on"

        contact_form = ContactForm(
        first_name=first_name,
        last_name=last_name,
        email=email,
        phone_number=phone,
        find=find,
        additional_info=info,
        file=file,
        terms=term
        )

        contact_form.save()

        # Do something with the form data, such as sending an email or saving it to the database
        
        # Redirect to a success page
        return render(request, 'base/contact_submit.html')

    # If the request is not a POST, return the form template
    return render(request, 'base/contact.html')

Django2/personalWeb/base/templates/base/IBMppt.html
{% extends 'main.html'%}

{% load static %}



{% block content %}
<div class="container text-center">
    <h2>IBM Presentation</h2>
</div>

<div class="container text-center">
    <iframe src="{% static 'base/IBMppt.pdf' %}" frameborder="0" width="1100" height="670">IBM</iframe>
</div>

<hr>

<div class="container">
    <h2>Python Libraries Used</h2>
    <ul>
        <li>Dash</li>
        <li>Folium</li>
        <li>Pandas</li>
        <li>Plotly</li>
        <li>Seaborn</li>
        <li>Scikit-learn</li>
    </ul>
</div>

<hr>

{% endblock %}

Django2/personalWeb/base/templates/base/cert.html
<!-- Inheriting from main.html in the main project folder-->
{% extends 'main.html'%}
{% load static %}

{% block content %}


<!--- Adding Publication Model -->

<div class="container">
    <h1 class="text-center">Certification</h1>
    {% for c in certs %}
    <hr>
    <div class="row">
        <div class="col-6">
            <h2><a href = "{{c.url}}" target ="_blank">{{c.title}}</a></h2>
        </div>
        <div class="col-6">
            <span class="float-right">{{c.date}}</span>
        </div>
    </div>

    {% endfor %}
</div>


<hr>

{% endblock %}

Django2/personalWeb/base/templates/base/contact.html
<!-- Inheriting from main.html in the main project folder-->
{% extends 'main.html'%}

{% load static %}



{% block content %}
<link rel="stylesheet" href="{% static 'base/contact.css' %}">

<div class="container">
    <h1 class="text-center">Contact Us</h1>
    <p class="text-center">Please fill out the form below to contact me!</p>
    <div class="form">
        <form action="{% url 'base:contact_submit' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset>
                <label>First Name: <input name="firstName" type="text" required></label>
                <label>Last Name: <input name="lastName" type="text" required></label>
            </fieldset>
            <fieldset>
                <label>Email Address: <input name="email" type="email" required></label>
                <label>Phone Number: <input name="phone" type="tel" required></label>
            </fieldset>
            <fieldset>
                <label>How did you find this website?
                    <select name="find">
                        <option value="">Select</option>
                        <option value=1>LinkedIn</option>
                        <option value=2>Resume</option>
                        <option value=3>GitHub</option>
                        <option value=4>Other</option>
                    </select>
                </label>
                <label>Additional Infomation: <textarea name="textBox" rows="3" placeholder="If you have something you like me to know..."></textarea></label>
                <label>Upload File: <input name="file" type="file"></label>
            </fieldset>

            <fieldset>
                <label><input class='term' name="term" type="checkbox">I agree to the <a href=''>terms and conditions</a></label>
            </fieldset>
            <button id="submit">Submit</button>
        </form>
    </div>
</div>

{% endblock %}

Django2/personalWeb/base/templates/base/contact_submit.html
<!-- Inheriting from main.html in the main project folder-->
{% extends 'main.html'%}

{% load static %}


{% block content %}
    <div class="container">
        <h1 class="text-center">Contact Us</h1>
        <p class="text-center">Thank you for reaching out! Your message has been received.</p>
    </div>
{% endblock %}

Django2/personalWeb/base/templates/base/eid101.html
{% extends 'main.html'%}

{% load static %}



{% block content %}
<div class="container text-center">
    <h2>Low Cost Diabetes Management and Diagnostic Devices for the People of Kampala, Uganda</h2>
</div>


{% endblock %}

Django2/personalWeb/base/templates/base/home.html
<!-- Inheriting from main.html in the main project folder-->
{% extends 'main.html'%}
{% load static %}

{% block content %}

<br>

<div class="container">
    <div class="row">
        <h1 class="text-center" style="padding: 20px;"> Welcome to my Personal Website </h1>
        <br>
        <div class="col-8">
            <img src = "{% static 'base/DiscordIcon.png' %}" style="height: auto; width: 100%; object-fit: contain">
        </div>
        <div class="col-4">
            <h3 class="text-center">About me</h3>
            <p style="text-align: justify">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed auctor augue ut nibh dictum, eget fermentum est aliquam. Fusce velit velit, condimentum vel velit eget, auctor suscipit augue. Sed at ante viverra, lobortis risus at, fermentum dolor. Sed id viverra elit, eget malesuada magna. Sed auctor, odio in tempus feugiat, odio nulla aliquet dolor, non facilisis ipsum orci eget magna. Sed non risus vitae mi feugiat commodo. Sed euismod, lorem id fringilla tempus, ante elit suscipit erat, euismod pharetra est elit.
            </p>
        </div>

    </div>
</div>

<hr>

<div class="container text-center">
    <h2>Skills</h2>
    {% for skill in skills %}
        <span>{{skill.title}}{% if not forloop.last %},{% endif %}</span>
    {% endfor %}

</div>

<hr>

<!--- Adding Project Model -->
<br>
<div class="container">
    <h2 class="text-center">Projects</h2>
    <div class="row">
        {% for project in projects %}
            {% if forloop.counter0|divisibleby:3 %}
                </div>
                <div class="row">
                
            {% endif %}
                <div class="col-4">
                    <h3 class="text-center" style="height: 80px;">
                        <a href = "{{project.url}}" style="text-decoration: none; color: black;">{{project.title}}</a>
                    </h3>
                    <a href = "{{project.url}}" style="height: 350px">
                        <img src = "{{project.image.url}}" style="height: 300px; width: 100%; object-fit: contain">
                    </a>

                    <p style="text-align: justify; min-height: 160px;">{{project.description}}</p>
                </div>
        {% endfor %}
    </div>
</div>
  


<hr>

{% endblock %}

Django2/personalWeb/base/templates/base/landing.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.rtl.min.css" integrity="sha384-WJUUqfoMmnfkBLne5uxXj+na/c7sesSJ32gI7GfCk4zO4GthUKhSEGyvQ839BC51" crossorigin="anonymous">

        <title>Chris Chan</title>
    </head>
    <body class="" style="align-items:center; width: 100%; height: 100%; background-color: lightgray; text-align: center;">

        <link rel="stylesheet" href="{% static 'base/landing.css' %}">
        <div> 
            <h2> This website is still in development and updates will be released frequently... </h2>
            <a href ="{% url 'base:home' %}">Homepage</a>
        </div>


    </body>
</html>

Django2/personalWeb/base/templates/base/mlproj.html
<!-- Inheriting from main.html in the main project folder-->
{% extends 'main.html'%}
{% load static %}

{% block content %}


<!--- Adding Publication Model -->

<div class="container">
    <ul>
        <li>Defining the problem statement</li>
        <li>Collecting the data</li>
        <li>Cleaning the data</li>
        <li>Modeling the data</li>
        <li>Model building</li>
        <li>Visualizing the data</div>
        <li>Model Deployment</li>
    </ul>
</div>

<div class="container">
    <h1 class="text-center">Machine Learning Projects</h1>
    {% for m in MLs %}
    <hr>
    <div class="row">
        <h2><a href = "{{m.url}}" target ="_blank">{{m.title}}</a></h2>
        </p>{{m.description|truncatechars:500}}</p>
        <img src = "{{m.image.url}}" style="height: 300px; object-fit: contain">
    </div>

    {% endfor %}
</div>


<hr>

{% endblock %}

Django2/personalWeb/base/templates/base/publication.html
<!-- Inheriting from main.html in the main project folder-->
{% extends 'main.html'%}
{% load static %}

{% block content %}


<!--- Adding Publication Model -->

<div class="container">
    <h1 class="text-center">My Publications</h1>
    {% for p in publications %}
    <hr>
    <div class="row">
        <h2><a href = "{{p.url}}" target ="_blank">{{p.title}}</a></h2>
        </p>{{p.description|truncatechars:500}}</p>
        <img src = "{{p.image.url}}" style="height: 300px; object-fit: contain">
    </div>

    {% endfor %}
</div>


<hr>

{% endblock %}

Django2/personalWeb/base/templates/base/resume.html
{% extends 'main.html'%}

{% load static %}



{% block content %}
<div class="container text-center">
    <h2>Resume</h2>
</div>

<div class="container text-center">
    <iframe src="{% static 'base/Chan Christopher Resume 2023.pdf' %}" width="800" height="1100"></iframe>
</div>
<hr>
{% endblock %}

Django2/personalWeb/base/templates/base/room.html
{% extends 'main.html'%}


{% block content %}

<h1> This is the room page </h1>

{% endblock %}