Django2/personalWeb/pdf/urls.py
from django.urls import path
from . import views

# Assign appname for clarity
app_name = "pdf"

urlpatterns = [
    path('', views.pdf, name="pdf"),
] 

Django2/personalWeb/personalWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('blog/', include('blog.urls')),
    path('stock/', include('stock.urls')),
    path('todo/', include('todo.urls')),
    path('utube/', include('utube.urls')),
    path('pdf/', include('pdf.urls')),
    path('expense/', include('expense.urls')),
    path('heartattackclassification/', include('heartattackclassification.urls')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django2/personalWeb/stock/urls.py
from django.urls import path
from . import views

# Assign appname for clarity
app_name = "stock"


urlpatterns = [
    path('', views.index, name='index'),
    path('info/', views.info, name='info'),
]

Django2/personalWeb/stock/models.py
from django.db import models
from datetime import datetime
# Create your models here.

class Stock(models.Model):
    symbol = models.CharField(max_length=10)
    name = models.CharField(max_length=100, default='U')
    price = models.FloatField()
    change = models.FloatField(default=0)
    date = models.DateTimeField(default=datetime.now)

    def __str__(self):
        return self.symbol

Django2/personalWeb/stock/views.py
from django.shortcuts import render
from .models import Stock
import requests
from django.conf import settings
import requests


# Create your views here.



def index(request):
    stocks = Stock.objects.all()
    return render(request, 'stock/index.html', {'stocks': stocks})

def info(request):
    return render(request, 'stock/info.html')

from datetime import datetime, timedelta

stocks = ['AAPL', 'GOOG', 'MSFT', 'SPY']

def update_stocks(time_period, stocks):
    Stock.objects.all().delete() # delete existing objects
    api_key = 'EEO2XGZO5KO1BBJI'
    for symbol in stocks:
        response = requests.get(f'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY_ADJUSTED&symbol={symbol}&apikey={api_key}&outputsize=full')
        data = response.json()
        try:
            daily_data = data['Time Series (Daily)']
            for date in daily_data:
                date_obj = datetime.strptime(date, '%Y-%m-%d')
                if (datetime.now() - date_obj).days > time_period:
                    break
                Stock.objects.create(
                    symbol=symbol,
                    name=data['Meta Data']['2. Symbol'],
                    date=datetime.strptime(date, '%Y-%m-%d'),
                    price=daily_data[date]['4. close']
                )
        except KeyError as e:
            print(f"Key error: {e}")
            print(data)

update_stocks(7, stocks)

import seaborn as sns
import matplotlib.pyplot as plt

def plot_stock_prices(symbol):
    plt.clf()
    stocks = Stock.objects.filter(symbol=symbol)
    prices = [stock.price for stock in stocks]
    dates = [stock.date for stock in stocks]

    sns.lineplot(x=dates, y=prices)
    plt.title(f"{symbol} Stock Price Trends")
    plt.xlabel("Date")
    plt.ylabel("Price")
    plt.savefig(f'stock/static/stock/{symbol}_plot.png')

for symbol in stocks:
    plot_stock_prices(symbol)

Django2/personalWeb/stock/templates/stock/index.html
<!-- Inheriting from main.html in the main project folder-->
{% extends 'main.html'%}
{% load static %}

{% block content %} 
<h1>Stocks</h1>

<div class="container">
  <div class="row">

    <div class="col-md-2">
      <table>
        <tr>
          <th>Symbol</th>
          <th>Date</th>
          <th>Price</th>
        </tr>
        {% for stock in stocks %}
          <tr>
            <td>{{ stock.symbol }}</td>
            <td>{{ stock.date|date:"Y-m-d"  }}</td>
            <td>{{ stock.price }}</td>
          </tr>
        {% endfor %}
      </table>
    </div>
    
    <div class="col-md-10">
      <div class="container">
        <div class="row">

          <div class="col-sm-6">
            <img src="{% static 'stock/AAPL_plot.png' %}" alt="AAPL stock plot" width="500px">
            <img src="{% static 'stock/SPY_plot.png' %}" alt="AMZN stock plot" width="500px">
          </div>

          <div class="col-sm-6">
            <img src="{% static 'stock/GOOG_plot.png' %}" alt="GOOG stock plot" width="500px">
            <img src="{% static 'stock/MSFT_plot.png' %}" alt="MSFT stock plot" width="500px">
          </div>
          
        </div>
      </div>
    </div>

  </div>
</div>

<hr>

<div class="container">
  <a href="{% url 'stock:info' %}">Info Page</a>
</div>

<hr>


{% endblock %}

Django2/personalWeb/stock/templates/stock/info.html
<!-- Inheriting from main.html in the main project folder-->
{% extends 'main.html'%}
{% load static %}

{% block content %} 
<div class="container text-center">

    <h1>Stocks Info Page</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quam nisi, facilisis et est at, tristique feugiat nisl. Proin vestibulum rhoncus diam, a auctor nunc dapibus ac. Fusce varius, ipsum vitae laoreet aliquet, enim metus convallis libero, id tempor ipsum ante id sapien. In condimentum, quam eu congue semper, velit velit tincidunt risus, vel interdum lectus nulla quis risus. Vivamus finibus consectetur lacus, id mollis orci eleifend at. Sed eget mi at magna egestas placerat auctor vitae tellus. Quisque congue ex id odio iaculis, a laoreet erat pellentesque. Nullam bibendum sapien vel tellus bibendum commodo. Integer ullamcorper, nibh vel rutrum placerat, ipsum nisi facilisis lectus, vel pharetra elit lectus et tellus. Nunc eget hendrerit quam, vel tincidunt diam.</p>

</div>

<hr>

{% endblock %}